# [[fields]]
# name = "Name"
# type = "name"

# [[fields]]
# name = "Surname"
# type = "surname"

# [[fields]]
# name = "Employment Company"
# type = "company"

# [[fields]]
# name = "Salary"
# type = "salary"
# min = 30000
# max = 150000

# [[fields]]
# name = "Age"
# type = "integer"
# min = 18
# max = 65

[[fields]]
name = "URL"
type = "url"